# Generated by Django 2.2.9 on 2022-05-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220520_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='slug', max_length=200, unique=True, verbose_name='ссылка1'),
        ),
    ]
