# Generated by Django 2.2.16 on 2022-06-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20220608_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text2',
            new_name='text',
        ),
    ]
